# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    container_name: "sponsor-db"
    restart: always
    user: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./seed_scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: sponsor_hunt
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    # this is for local db seeding purposes
    ports:
      - "5432:5432"

volumes:
  db-data:
